#!/bin/bash
set -e

[ -z "$KEEPDEST" ] && \
	rm -rf "$DEST"

(
	source "${MAKEDIR}/.binary-setup"
	export BINARY_SHORT_NAME="$DOCKER_MONITOR_BINARY_NAME"
	export GO_PACKAGE='./cmd/monitor/monitor.go'
	source "${MAKEDIR}/.binary"
)

(
	source "${MAKEDIR}/.binary-setup"
	export BINARY_SHORT_NAME="$DOCKER_MONITOR_NET_BINARY_NAME"
	export GO_PACKAGE='./monitor/monitor_net.go'
	source "${MAKEDIR}/.binary"
)