#!/bin/bash
set -e

[ -z "$KEEPDEST" ] && \
	rm -rf "$DEST"

(
	source "${MAKEDIR}/.binary-setup"
	export BINARY_SHORT_NAME="$DOCKER_MONITOR_BINARY_NAME"
	export GO_PACKAGE='github.com/vislee/docker/cmd/monitor'
	source "${MAKEDIR}/.binary"
)